# Generated by Django 3.0.2 on 2020-03-19 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('appointment_subject', models.TextField()),
                ('appointment_assigned_to', models.IntegerField(choices=[('TIER 1', 'TIER 1'), ('TIER 2', 'TIER 2'), ('TIER 3', 'TIER 3')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment_User_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
