# Generated by Django 3.0.2 on 2020-03-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_assigned_to',
            field=models.IntegerField(choices=[('TIER1', 'TIER1'), ('TIER2', 'TIER2'), ('TIER3', 'TIER3')]),
        ),
    ]
