# Generated by Django 3.0.2 on 2020-03-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0003_auto_20200322_1236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
