# Generated by Django 3.0.2 on 2020-04-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='from_account',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='to_account',
            field=models.CharField(max_length=20),
        ),
    ]
