# Generated by Django 3.0.2 on 2020-03-31 23:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProfileUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField()),
                ('username', models.CharField(default='', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_transaction', models.BooleanField()),
                ('create_transaction', models.BooleanField()),
                ('authorize_transaction', models.BooleanField()),
                ('transaction_type', models.CharField(max_length=20)),
                ('issue_check', models.BooleanField()),
                ('fund_transfer', models.BooleanField()),
                ('view_account', models.BooleanField()),
                ('create_account', models.BooleanField()),
                ('modify_account', models.BooleanField()),
                ('close_account', models.BooleanField()),
                ('delete_account', models.BooleanField()),
                ('access_logs', models.BooleanField()),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.IntegerField()),
                ('to_account', models.IntegerField()),
                ('transaction_value', models.BigIntegerField()),
                ('transaction_date', models.DateTimeField()),
                ('transaction_type', models.CharField(max_length=20)),
                ('transaction_status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_User_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField()),
                ('request_subject', models.TextField()),
                ('request_assigned_to', models.IntegerField()),
                ('request_type', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Requests_User_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('birthdate', models.DateTimeField()),
                ('ssn', models.CharField(max_length=9, unique=True)),
                ('joining_date', models.DateTimeField(default=datetime.datetime.now)),
                ('flag', models.BooleanField(default=False)),
                ('privilege_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ProfilePrivilege', to='home.Privilege')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('appointment_subject', models.TextField()),
                ('appointment_assigned_to', models.CharField(choices=[('TIER1', 'TIER1'), ('TIER2', 'TIER2'), ('TIER3', 'TIER3')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('savings', 'SAVINGS'), ('checking', 'CHECKING'), ('credit_card', 'CREDIT_CARD')], max_length=20)),
                ('account_balance', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('flag', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_User_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
