# Generated by Django 3.0.2 on 2020-02-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
    ]
