# Generated by Django 3.0.2 on 2020-04-02 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_status', models.CharField(choices=[('TIER1', 'TIER1'), ('TIER2', 'TIER2'), ('TIER3', 'TIER3')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='pendingprofileupdate',
            name='username',
        ),
        migrations.AddField(
            model_name='pendingprofileupdate',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Pprofile_User_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingprofileupdate',
            name='city',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='pendingprofileupdate',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='pendingprofileupdate',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='pendingprofileupdate',
            name='state',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ssn',
            field=models.IntegerField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_value',
            field=models.FloatField(),
        ),
    ]
