# Generated by Django 3.0.2 on 2020-03-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingprofileupdate',
            name='id',
        ),
        migrations.AlterField(
            model_name='pendingprofileupdate',
            name='username',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
