# Generated by Django 3.0.2 on 2020-04-01 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20200331_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingprofileupdate',
            name='username',
        ),
        migrations.AddField(
            model_name='pendingprofileupdate',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingprofileupdate',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Pprofile_User_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
