# Generated by Django 3.0.2 on 2020-04-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_assigned_to',
        ),
    ]
