# Generated by Django 3.0.2 on 2020-04-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_appointment_appointment_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingprofileupdate',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='tier_status',
            field=models.CharField(choices=[('Tier_1', 'Tier_1'), ('Tier_2', 'Tier_2'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
