# Generated by Django 3.0.2 on 2020-04-01 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200401_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingprofileupdate',
            name='city',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='pendingprofileupdate',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='pendingprofileupdate',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='pendingprofileupdate',
            name='state',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='pendingprofileupdate',
            name='street_address',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ssn',
            field=models.IntegerField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street_address',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_value',
            field=models.FloatField(),
        ),
    ]
