# Generated by Django 3.0.2 on 2020-03-22 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200322_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=uuid.UUID('d33a1a68-0501-49e0-8489-601c0358bb6a'), max_length=10, unique=True),
        ),
    ]
