# Generated by Django 3.0.2 on 2020-04-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200401_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingprofileupdate',
            name='street_address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street_address',
            field=models.CharField(max_length=20),
        ),
    ]
