# Generated by Django 3.0.2 on 2020-03-22 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=uuid.UUID('9054777c-c936-49fd-83f7-6428aad11ddb'), max_length=10, unique=True),
        ),
    ]
