# Generated by Django 3.0.2 on 2020-03-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200322_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=4020161307, max_length=10, unique=True),
        ),
    ]
