# Generated by Django 3.0.2 on 2020-03-25 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200322_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProfileUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.RemoveField(
            model_name='privilege',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='privilege',
            name='request_type',
        ),
        migrations.AddField(
            model_name='account',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='privilege_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ProfilePrivilege', to='home.Privilege'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
