# Generated by Django 3.0.2 on 2020-03-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200325_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingProfileUpdate',
        ),
    ]
