# Generated by Django 3.0.2 on 2020-03-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_pendingprofileupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingProfileUpdate',
        ),
    ]
