# Generated by Django 3.0.2 on 2020-03-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_delete_pendingprofileupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProfileUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
    ]
