# Generated by Django 3.0.2 on 2020-03-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_pendingprofileupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
