# Generated by Django 3.0.2 on 2020-03-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20200325_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
