# Generated by Django 3.0.2 on 2020-03-26 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20200325_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_transaction', models.BooleanField()),
                ('create_transaction', models.BooleanField()),
                ('authorize_transaction', models.BooleanField()),
                ('transaction_type', models.CharField(max_length=20)),
                ('issue_check', models.BooleanField()),
                ('fund_transfer', models.BooleanField()),
                ('view_account', models.BooleanField()),
                ('create_account', models.BooleanField()),
                ('modify_account', models.BooleanField()),
                ('close_account', models.BooleanField()),
                ('delete_account', models.BooleanField()),
                ('access_logs', models.BooleanField()),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='privilege_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ProfilePrivilege', to='home.Privilege'),
        ),
    ]
