# Generated by Django 3.0.2 on 2020-03-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20200325_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_balance',
            field=models.FloatField(default=0),
        ),
    ]
