# Generated by Django 3.0.2 on 2020-04-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20200328_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingprofileupdate',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='pendingprofileupdate',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ssn',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
