# Generated by Django 3.0.2 on 2020-04-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20200330_1058'),
        ('home', '0035_auto_20200401_0134'),
    ]

    operations = [
    ]
