# Generated by Django 3.0.2 on 2020-04-02 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0036_merge_20200401_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='delete',
            new_name='to_delete',
        ),
        migrations.RemoveField(
            model_name='pendingprofileupdate',
            name='username',
        ),
        migrations.AddField(
            model_name='pendingprofileupdate',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingprofileupdate',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pending_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='tier_status',
            field=models.CharField(choices=[('Tier_1', 'Tier_1'), ('Tier_2', 'Tier_2'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
